version: 0.2
   
phases: 
  install: 
    commands: 
      - echo entered into install phase
  pre_build: 
    commands: 
      - echo 'entered into pre_build phase'

  build: 
    commands: 
      - echo 'entered into build phase'  
      - sed -i 's/conduit.productionready.io/backend_IP:3000/' src/agent.js

  post_build: 
    commands: 
       - echo 'entered into post_build phase'    

artifacts: 
  files: '**/*'  
